# Site settings
title: ATFD Blog
subtitle: by ATFD
email: emailaddress@gmail.com
description: A place for notes
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: New York
state: NY
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown
