# Site settings
title: ATFD
subtitle: by atfd
email: emailaddress@gmail.com
description: A place for notes
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown
